# Generated by Django 5.0.2 on 2024-03-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nmapinfo',
            name='nmape',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
