# Generated by Django 5.0.2 on 2024-03-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_nmapinfo_nmape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpsinfo',
            name='wpss',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
