# Generated by Django 5.0.2 on 2024-03-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_wpsinfo_wpss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crti_info',
            name='cetiddata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
