# Generated by Django 5.0.2 on 2024-03-03 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_domain_domain_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
